package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AntecedentesPersonales generated by hbm2java
 */
@Entity
@Table(name="antecedentes_personales"
    ,schema="public"
)
public class AntecedentesPersonales  implements java.io.Serializable {


     private int apId;
     private Paciente paciente;
     private UnidadTiempo unidadTiempoByApUnidadFrecuenciaCigarillo;
     private UnidadTiempo unidadTiempoByApUnidadFrecuenciaLicor;
     private UnidadTiempo unidadTiempoByApUnidadHaceCuantoLicor;
     private UnidadTiempo unidadTiempoByApUnidadFrecuenciaOtrasSustancias;
     private UnidadTiempo unidadTiempoByApUnidadHaceCuantoOtrasSustancias;
     private UnidadTiempo unidadTiempoByApUnidadFrecuenciaActividadFisica;
     private UnidadTiempo unidadTiempoByApUnidadHaceCuantoCigarillo;
     private Boolean apInfarto;
     private Boolean apHipertension;
     private Boolean apDiabetes;
     private Boolean apAcv;
     private Boolean apFumaCigarrillo;
     private Integer apFrecuenciaCigarrillo;
     private Integer apHaceCuantoCigarrillo;
     private Boolean apConviveConFumadores;
     private Boolean apConsumeLicor;
     private Integer apFrecuenciaLicor;
     private Integer apHaceCuantoLicor;
     private Boolean apConsumeOtrasSustancias;
     private Integer apFrecuenciaOtrasSustancias;
     private Integer apHaceCuantoOtrasSustancias;
     private Boolean apActividadFisica;
     private Integer apFrecuenciaActividadFisica;
     private String apMedicamentos;

    public AntecedentesPersonales() {
    }

	
    public AntecedentesPersonales(Paciente paciente) {
        this.paciente = paciente;
    }
    public AntecedentesPersonales(Paciente paciente, UnidadTiempo unidadTiempoByApUnidadFrecuenciaCigarillo, UnidadTiempo unidadTiempoByApUnidadFrecuenciaLicor, UnidadTiempo unidadTiempoByApUnidadHaceCuantoLicor, UnidadTiempo unidadTiempoByApUnidadFrecuenciaOtrasSustancias, UnidadTiempo unidadTiempoByApUnidadHaceCuantoOtrasSustancias, UnidadTiempo unidadTiempoByApUnidadFrecuenciaActividadFisica, UnidadTiempo unidadTiempoByApUnidadHaceCuantoCigarillo, Boolean apInfarto, Boolean apHipertension, Boolean apDiabetes, Boolean apAcv, Boolean apFumaCigarrillo, Integer apFrecuenciaCigarrillo, Integer apHaceCuantoCigarrillo, Boolean apConviveConFumadores, Boolean apConsumeLicor, Integer apFrecuenciaLicor, Integer apHaceCuantoLicor, Boolean apConsumeOtrasSustancias, Integer apFrecuenciaOtrasSustancias, Integer apHaceCuantoOtrasSustancias, Boolean apActividadFisica, Integer apFrecuenciaActividadFisica, String apMedicamentos) {
       this.paciente = paciente;
       this.unidadTiempoByApUnidadFrecuenciaCigarillo = unidadTiempoByApUnidadFrecuenciaCigarillo;
       this.unidadTiempoByApUnidadFrecuenciaLicor = unidadTiempoByApUnidadFrecuenciaLicor;
       this.unidadTiempoByApUnidadHaceCuantoLicor = unidadTiempoByApUnidadHaceCuantoLicor;
       this.unidadTiempoByApUnidadFrecuenciaOtrasSustancias = unidadTiempoByApUnidadFrecuenciaOtrasSustancias;
       this.unidadTiempoByApUnidadHaceCuantoOtrasSustancias = unidadTiempoByApUnidadHaceCuantoOtrasSustancias;
       this.unidadTiempoByApUnidadFrecuenciaActividadFisica = unidadTiempoByApUnidadFrecuenciaActividadFisica;
       this.unidadTiempoByApUnidadHaceCuantoCigarillo = unidadTiempoByApUnidadHaceCuantoCigarillo;
       this.apInfarto = apInfarto;
       this.apHipertension = apHipertension;
       this.apDiabetes = apDiabetes;
       this.apAcv = apAcv;
       this.apFumaCigarrillo = apFumaCigarrillo;
       this.apFrecuenciaCigarrillo = apFrecuenciaCigarrillo;
       this.apHaceCuantoCigarrillo = apHaceCuantoCigarrillo;
       this.apConviveConFumadores = apConviveConFumadores;
       this.apConsumeLicor = apConsumeLicor;
       this.apFrecuenciaLicor = apFrecuenciaLicor;
       this.apHaceCuantoLicor = apHaceCuantoLicor;
       this.apConsumeOtrasSustancias = apConsumeOtrasSustancias;
       this.apFrecuenciaOtrasSustancias = apFrecuenciaOtrasSustancias;
       this.apHaceCuantoOtrasSustancias = apHaceCuantoOtrasSustancias;
       this.apActividadFisica = apActividadFisica;
       this.apFrecuenciaActividadFisica = apFrecuenciaActividadFisica;
       this.apMedicamentos = apMedicamentos;
    }
   
    @Id 
    @SequenceGenerator(name="pk_sequence",sequenceName="entity_id_seq", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
    @Column(name="ap_id", nullable=false)
    public int getApId() {
        return this.apId;
    }
    
    public void setApId(int apId) {
        this.apId = apId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_id_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_frecuencia_cigarillo")
    public UnidadTiempo getUnidadTiempoByApUnidadFrecuenciaCigarillo() {
        return this.unidadTiempoByApUnidadFrecuenciaCigarillo;
    }
    
    public void setUnidadTiempoByApUnidadFrecuenciaCigarillo(UnidadTiempo unidadTiempoByApUnidadFrecuenciaCigarillo) {
        this.unidadTiempoByApUnidadFrecuenciaCigarillo = unidadTiempoByApUnidadFrecuenciaCigarillo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_frecuencia_licor")
    public UnidadTiempo getUnidadTiempoByApUnidadFrecuenciaLicor() {
        return this.unidadTiempoByApUnidadFrecuenciaLicor;
    }
    
    public void setUnidadTiempoByApUnidadFrecuenciaLicor(UnidadTiempo unidadTiempoByApUnidadFrecuenciaLicor) {
        this.unidadTiempoByApUnidadFrecuenciaLicor = unidadTiempoByApUnidadFrecuenciaLicor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_hace_cuanto_licor")
    public UnidadTiempo getUnidadTiempoByApUnidadHaceCuantoLicor() {
        return this.unidadTiempoByApUnidadHaceCuantoLicor;
    }
    
    public void setUnidadTiempoByApUnidadHaceCuantoLicor(UnidadTiempo unidadTiempoByApUnidadHaceCuantoLicor) {
        this.unidadTiempoByApUnidadHaceCuantoLicor = unidadTiempoByApUnidadHaceCuantoLicor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_frecuencia_otras_sustancias")
    public UnidadTiempo getUnidadTiempoByApUnidadFrecuenciaOtrasSustancias() {
        return this.unidadTiempoByApUnidadFrecuenciaOtrasSustancias;
    }
    
    public void setUnidadTiempoByApUnidadFrecuenciaOtrasSustancias(UnidadTiempo unidadTiempoByApUnidadFrecuenciaOtrasSustancias) {
        this.unidadTiempoByApUnidadFrecuenciaOtrasSustancias = unidadTiempoByApUnidadFrecuenciaOtrasSustancias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_hace_cuanto_otras_sustancias")
    public UnidadTiempo getUnidadTiempoByApUnidadHaceCuantoOtrasSustancias() {
        return this.unidadTiempoByApUnidadHaceCuantoOtrasSustancias;
    }
    
    public void setUnidadTiempoByApUnidadHaceCuantoOtrasSustancias(UnidadTiempo unidadTiempoByApUnidadHaceCuantoOtrasSustancias) {
        this.unidadTiempoByApUnidadHaceCuantoOtrasSustancias = unidadTiempoByApUnidadHaceCuantoOtrasSustancias;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_frecuencia_actividad_fisica")
    public UnidadTiempo getUnidadTiempoByApUnidadFrecuenciaActividadFisica() {
        return this.unidadTiempoByApUnidadFrecuenciaActividadFisica;
    }
    
    public void setUnidadTiempoByApUnidadFrecuenciaActividadFisica(UnidadTiempo unidadTiempoByApUnidadFrecuenciaActividadFisica) {
        this.unidadTiempoByApUnidadFrecuenciaActividadFisica = unidadTiempoByApUnidadFrecuenciaActividadFisica;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ap_unidad_hace_cuanto_cigarillo")
    public UnidadTiempo getUnidadTiempoByApUnidadHaceCuantoCigarillo() {
        return this.unidadTiempoByApUnidadHaceCuantoCigarillo;
    }
    
    public void setUnidadTiempoByApUnidadHaceCuantoCigarillo(UnidadTiempo unidadTiempoByApUnidadHaceCuantoCigarillo) {
        this.unidadTiempoByApUnidadHaceCuantoCigarillo = unidadTiempoByApUnidadHaceCuantoCigarillo;
    }

    
    @Column(name="ap_infarto")
    public Boolean getApInfarto() {
        return this.apInfarto;
    }
    
    public void setApInfarto(Boolean apInfarto) {
        this.apInfarto = apInfarto;
    }

    
    @Column(name="ap_hipertension")
    public Boolean getApHipertension() {
        return this.apHipertension;
    }
    
    public void setApHipertension(Boolean apHipertension) {
        this.apHipertension = apHipertension;
    }

    
    @Column(name="ap_diabetes")
    public Boolean getApDiabetes() {
        return this.apDiabetes;
    }
    
    public void setApDiabetes(Boolean apDiabetes) {
        this.apDiabetes = apDiabetes;
    }

    
    @Column(name="ap_acv")
    public Boolean getApAcv() {
        return this.apAcv;
    }
    
    public void setApAcv(Boolean apAcv) {
        this.apAcv = apAcv;
    }

    
    @Column(name="ap_fuma_cigarrillo")
    public Boolean getApFumaCigarrillo() {
        return this.apFumaCigarrillo;
    }
    
    public void setApFumaCigarrillo(Boolean apFumaCigarrillo) {
        this.apFumaCigarrillo = apFumaCigarrillo;
    }

    
    @Column(name="ap_frecuencia_cigarrillo")
    public Integer getApFrecuenciaCigarrillo() {
        return this.apFrecuenciaCigarrillo;
    }
    
    public void setApFrecuenciaCigarrillo(Integer apFrecuenciaCigarrillo) {
        this.apFrecuenciaCigarrillo = apFrecuenciaCigarrillo;
    }

    
    @Column(name="ap_hace_cuanto_cigarrillo")
    public Integer getApHaceCuantoCigarrillo() {
        return this.apHaceCuantoCigarrillo;
    }
    
    public void setApHaceCuantoCigarrillo(Integer apHaceCuantoCigarrillo) {
        this.apHaceCuantoCigarrillo = apHaceCuantoCigarrillo;
    }

    
    @Column(name="ap_convive_con_fumadores")
    public Boolean getApConviveConFumadores() {
        return this.apConviveConFumadores;
    }
    
    public void setApConviveConFumadores(Boolean apConviveConFumadores) {
        this.apConviveConFumadores = apConviveConFumadores;
    }

    
    @Column(name="ap_consume_licor")
    public Boolean getApConsumeLicor() {
        return this.apConsumeLicor;
    }
    
    public void setApConsumeLicor(Boolean apConsumeLicor) {
        this.apConsumeLicor = apConsumeLicor;
    }

    
    @Column(name="ap_frecuencia_licor")
    public Integer getApFrecuenciaLicor() {
        return this.apFrecuenciaLicor;
    }
    
    public void setApFrecuenciaLicor(Integer apFrecuenciaLicor) {
        this.apFrecuenciaLicor = apFrecuenciaLicor;
    }

    
    @Column(name="ap_hace_cuanto_licor")
    public Integer getApHaceCuantoLicor() {
        return this.apHaceCuantoLicor;
    }
    
    public void setApHaceCuantoLicor(Integer apHaceCuantoLicor) {
        this.apHaceCuantoLicor = apHaceCuantoLicor;
    }

    
    @Column(name="ap_consume_otras_sustancias")
    public Boolean getApConsumeOtrasSustancias() {
        return this.apConsumeOtrasSustancias;
    }
    
    public void setApConsumeOtrasSustancias(Boolean apConsumeOtrasSustancias) {
        this.apConsumeOtrasSustancias = apConsumeOtrasSustancias;
    }

    
    @Column(name="ap_frecuencia_otras_sustancias")
    public Integer getApFrecuenciaOtrasSustancias() {
        return this.apFrecuenciaOtrasSustancias;
    }
    
    public void setApFrecuenciaOtrasSustancias(Integer apFrecuenciaOtrasSustancias) {
        this.apFrecuenciaOtrasSustancias = apFrecuenciaOtrasSustancias;
    }

    
    @Column(name="ap_hace_cuanto_otras_sustancias")
    public Integer getApHaceCuantoOtrasSustancias() {
        return this.apHaceCuantoOtrasSustancias;
    }
    
    public void setApHaceCuantoOtrasSustancias(Integer apHaceCuantoOtrasSustancias) {
        this.apHaceCuantoOtrasSustancias = apHaceCuantoOtrasSustancias;
    }

    
    @Column(name="ap_actividad_fisica")
    public Boolean getApActividadFisica() {
        return this.apActividadFisica;
    }
    
    public void setApActividadFisica(Boolean apActividadFisica) {
        this.apActividadFisica = apActividadFisica;
    }

    
    @Column(name="ap_frecuencia_actividad_fisica")
    public Integer getApFrecuenciaActividadFisica() {
        return this.apFrecuenciaActividadFisica;
    }
    
    public void setApFrecuenciaActividadFisica(Integer apFrecuenciaActividadFisica) {
        this.apFrecuenciaActividadFisica = apFrecuenciaActividadFisica;
    }

    
    @Column(name="ap_medicamentos", length=500)
    public String getApMedicamentos() {
        return this.apMedicamentos;
    }
    
    public void setApMedicamentos(String apMedicamentos) {
        this.apMedicamentos = apMedicamentos;
    }




}


