package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AntecedentesFamiliares generated by hbm2java
 */
@Entity
@Table(name="antecedentes_familiares"
    ,schema="public"
)
public class AntecedentesFamiliares  implements java.io.Serializable {

    private int afId;
    private Paciente paciente;
    private Boolean afAbuelosInfarto;
    private Boolean afPadresInfarto;
    private Boolean afTiosInfarto;
    private Boolean afHermanosInfarto;
    private Boolean afAbuelosDiabetes;
    private Boolean afPadresDiabetes;
    private Boolean afTiosDiabetes;
    private Boolean afHermanosDiabetes;
    private Boolean afAbuelosHipertension;
    private Boolean afPadresHipertension;
    private Boolean afTiosHipertension;
    private Boolean afHermanosHipertension;
    private Boolean afAbuelosAcv;
    private Boolean afPadresAcv;
    private Boolean afTiosAcv;
    private Boolean afHermanosAcv;

    public AntecedentesFamiliares() {
    }

	
    public AntecedentesFamiliares(Paciente paciente) {
        this.paciente = paciente;
    }
    public AntecedentesFamiliares(Paciente paciente, Boolean afAbuelosInfarto, Boolean afPadresInfarto, Boolean afTiosInfarto, Boolean afHermanosInfarto, Boolean afAbuelosDiabetes, Boolean afPadresDiabetes, Boolean afTiosDiabetes, Boolean afHermanosDiabetes, Boolean afAbuelosHipertension, Boolean afPadresHipertension, Boolean afTiosHipertension, Boolean afHermanosHipertension, Boolean afAbuelosAcv, Boolean afPadresAcv, Boolean afTiosAcv, Boolean afHermanosAcv) {
       this.paciente = paciente;
       this.afAbuelosInfarto = afAbuelosInfarto;
       this.afPadresInfarto = afPadresInfarto;
       this.afTiosInfarto = afTiosInfarto;
       this.afHermanosInfarto = afHermanosInfarto;
       this.afAbuelosDiabetes = afAbuelosDiabetes;
       this.afPadresDiabetes = afPadresDiabetes;
       this.afTiosDiabetes = afTiosDiabetes;
       this.afHermanosDiabetes = afHermanosDiabetes;
       this.afAbuelosHipertension = afAbuelosHipertension;
       this.afPadresHipertension = afPadresHipertension;
       this.afTiosHipertension = afTiosHipertension;
       this.afHermanosHipertension = afHermanosHipertension;
       this.afAbuelosAcv = afAbuelosAcv;
       this.afPadresAcv = afPadresAcv;
       this.afTiosAcv = afTiosAcv;
       this.afHermanosAcv = afHermanosAcv;
    }
   
    
    @Id
    @SequenceGenerator(name = "pk_sequence", sequenceName = "entity_id_seq", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
    @Column(name="af_id", nullable=false)
    public int getAfId() {
        return this.afId;
    }
    
    public void setAfId(int afId) {
        this.afId = afId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="af_id_paciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

    
    @Column(name="af_abuelos_infarto")
    public Boolean getAfAbuelosInfarto() {
        return this.afAbuelosInfarto;
    }
    
    public void setAfAbuelosInfarto(Boolean afAbuelosInfarto) {
        this.afAbuelosInfarto = afAbuelosInfarto;
    }

    
    @Column(name="af_padres_infarto")
    public Boolean getAfPadresInfarto() {
        return this.afPadresInfarto;
    }
    
    public void setAfPadresInfarto(Boolean afPadresInfarto) {
        this.afPadresInfarto = afPadresInfarto;
    }

    
    @Column(name="af_tios_infarto")
    public Boolean getAfTiosInfarto() {
        return this.afTiosInfarto;
    }
    
    public void setAfTiosInfarto(Boolean afTiosInfarto) {
        this.afTiosInfarto = afTiosInfarto;
    }

    
    @Column(name="af_hermanos_infarto")
    public Boolean getAfHermanosInfarto() {
        return this.afHermanosInfarto;
    }
    
    public void setAfHermanosInfarto(Boolean afHermanosInfarto) {
        this.afHermanosInfarto = afHermanosInfarto;
    }

    
    @Column(name="af_abuelos_diabetes")
    public Boolean getAfAbuelosDiabetes() {
        return this.afAbuelosDiabetes;
    }
    
    public void setAfAbuelosDiabetes(Boolean afAbuelosDiabetes) {
        this.afAbuelosDiabetes = afAbuelosDiabetes;
    }

    
    @Column(name="af_padres_diabetes")
    public Boolean getAfPadresDiabetes() {
        return this.afPadresDiabetes;
    }
    
    public void setAfPadresDiabetes(Boolean afPadresDiabetes) {
        this.afPadresDiabetes = afPadresDiabetes;
    }

    
    @Column(name="af_tios_diabetes")
    public Boolean getAfTiosDiabetes() {
        return this.afTiosDiabetes;
    }
    
    public void setAfTiosDiabetes(Boolean afTiosDiabetes) {
        this.afTiosDiabetes = afTiosDiabetes;
    }

    
    @Column(name="af_hermanos_diabetes")
    public Boolean getAfHermanosDiabetes() {
        return this.afHermanosDiabetes;
    }
    
    public void setAfHermanosDiabetes(Boolean afHermanosDiabetes) {
        this.afHermanosDiabetes = afHermanosDiabetes;
    }

    
    @Column(name="af_abuelos_hipertension")
    public Boolean getAfAbuelosHipertension() {
        return this.afAbuelosHipertension;
    }
    
    public void setAfAbuelosHipertension(Boolean afAbuelosHipertension) {
        this.afAbuelosHipertension = afAbuelosHipertension;
    }

    
    @Column(name="af_padres_hipertension")
    public Boolean getAfPadresHipertension() {
        return this.afPadresHipertension;
    }
    
    public void setAfPadresHipertension(Boolean afPadresHipertension) {
        this.afPadresHipertension = afPadresHipertension;
    }

    
    @Column(name="af_tios_hipertension")
    public Boolean getAfTiosHipertension() {
        return this.afTiosHipertension;
    }
    
    public void setAfTiosHipertension(Boolean afTiosHipertension) {
        this.afTiosHipertension = afTiosHipertension;
    }

    
    @Column(name="af_hermanos_hipertension")
    public Boolean getAfHermanosHipertension() {
        return this.afHermanosHipertension;
    }
    
    public void setAfHermanosHipertension(Boolean afHermanosHipertension) {
        this.afHermanosHipertension = afHermanosHipertension;
    }

    
    @Column(name="af_abuelos_acv")
    public Boolean getAfAbuelosAcv() {
        return this.afAbuelosAcv;
    }
    
    public void setAfAbuelosAcv(Boolean afAbuelosAcv) {
        this.afAbuelosAcv = afAbuelosAcv;
    }

    
    @Column(name="af_padres_acv")
    public Boolean getAfPadresAcv() {
        return this.afPadresAcv;
    }
    
    public void setAfPadresAcv(Boolean afPadresAcv) {
        this.afPadresAcv = afPadresAcv;
    }

    
    @Column(name="af_tios_acv")
    public Boolean getAfTiosAcv() {
        return this.afTiosAcv;
    }
    
    public void setAfTiosAcv(Boolean afTiosAcv) {
        this.afTiosAcv = afTiosAcv;
    }

    
    @Column(name="af_hermanos_acv")
    public Boolean getAfHermanosAcv() {
        return this.afHermanosAcv;
    }
    
    public void setAfHermanosAcv(Boolean afHermanosAcv) {
        this.afHermanosAcv = afHermanosAcv;
    }




}


