package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Auxiliar generated by hbm2java
 */
@Entity
@Table(name="auxiliar"
    ,schema="public"
)
public class Auxiliar  implements java.io.Serializable {


     private String auxId;
     private Login login;
     private String auxTipoId;
     private String auxApellido1;
     private String auxApellido2;
     private String auxNombres;
     private Date auxFechaRegistro;
     private boolean auxEstado;

    public Auxiliar() {
    }

    public Auxiliar(Login login, String auxTipoId, String auxApellido1, String auxApellido2, String auxNombres, Date auxFechaRegistro, boolean auxEstado) {
       this.login = login;
       this.auxTipoId = auxTipoId;
       this.auxApellido1 = auxApellido1;
       this.auxApellido2 = auxApellido2;
       this.auxNombres = auxNombres;
       this.auxFechaRegistro = auxFechaRegistro;
       this.auxEstado = auxEstado;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="login"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="aux_id", nullable=false, length=30)
    public String getAuxId() {
        return this.auxId;
    }
    
    public void setAuxId(String auxId) {
        this.auxId = auxId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="aux_tipo_id", nullable=false, length=10)
    public String getAuxTipoId() {
        return this.auxTipoId;
    }
    
    public void setAuxTipoId(String auxTipoId) {
        this.auxTipoId = auxTipoId;
    }

    
    @Column(name="aux_apellido1", nullable=false, length=50)
    public String getAuxApellido1() {
        return this.auxApellido1;
    }
    
    public void setAuxApellido1(String auxApellido1) {
        this.auxApellido1 = auxApellido1;
    }

    
    @Column(name="aux_apellido2", nullable=false, length=50)
    public String getAuxApellido2() {
        return this.auxApellido2;
    }
    
    public void setAuxApellido2(String auxApellido2) {
        this.auxApellido2 = auxApellido2;
    }

    
    @Column(name="aux_nombres", nullable=false, length=50)
    public String getAuxNombres() {
        return this.auxNombres;
    }
    
    public void setAuxNombres(String auxNombres) {
        this.auxNombres = auxNombres;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="aux_fecha_registro", nullable=false, length=13)
    public Date getAuxFechaRegistro() {
        return this.auxFechaRegistro;
    }
    
    public void setAuxFechaRegistro(Date auxFechaRegistro) {
        this.auxFechaRegistro = auxFechaRegistro;
    }

    
    @Column(name="aux_estado", nullable=false)
    public boolean isAuxEstado() {
        return this.auxEstado;
    }
    
    public void setAuxEstado(boolean auxEstado) {
        this.auxEstado = auxEstado;
    }




}


