package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name="log"
    ,schema="public"
)
public class Log  implements java.io.Serializable {


     private int idLog;
     private String tableNombre;
     private String operacion;
     private String oldValue;
     private String newValue;
     private String userName;
     private Date dateOperation;

    public Log() {
    }

	
    public Log(String tableNombre, String userName, Date dateOperation) {
        this.tableNombre = tableNombre;
        this.userName = userName;
        this.dateOperation = dateOperation;
    }
    public Log(String tableNombre, String operacion, String oldValue, String newValue, String userName, Date dateOperation) {
       this.tableNombre = tableNombre;
       this.operacion = operacion;
       this.oldValue = oldValue;
       this.newValue = newValue;
       this.userName = userName;
       this.dateOperation = dateOperation;
    }
   
    @Id 
    @SequenceGenerator(name="pk_sequence",sequenceName="entity_id_seq", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
    @Column(name="id_log", nullable=false)
    public int getIdLog() {
        return this.idLog;
    }
    
    public void setIdLog(int idLog) {
        this.idLog = idLog;
    }

    
    @Column(name="table_nombre", nullable=false, length=10)
    public String getTableNombre() {
        return this.tableNombre;
    }
    
    public void setTableNombre(String tableNombre) {
        this.tableNombre = tableNombre;
    }

    
    @Column(name="operacion", length=10)
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }

    
    @Column(name="old_value", length=100)
    public String getOldValue() {
        return this.oldValue;
    }
    
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue;
    }

    
    @Column(name="new_value", length=100)
    public String getNewValue() {
        return this.newValue;
    }
    
    public void setNewValue(String newValue) {
        this.newValue = newValue;
    }

    
    @Column(name="user_name", nullable=false, length=30)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_operation", nullable=false, length=13)
    public Date getDateOperation() {
        return this.dateOperation;
    }
    
    public void setDateOperation(Date dateOperation) {
        this.dateOperation = dateOperation;
    }




}


