package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,schema="public"
)
public class Login  implements java.io.Serializable {


     private String loginUser;
     private String loginPassword;
     private Auxiliar auxiliar;
     private Paciente paciente;

    public Login() {
    }

	
    public Login(String loginUser, String loginPassword) {
        this.loginUser = loginUser;
        this.loginPassword = loginPassword;
    }
    public Login(String loginUser, String loginPassword, Auxiliar auxiliar, Paciente paciente) {
       this.loginUser = loginUser;
       this.loginPassword = loginPassword;
       this.auxiliar = auxiliar;
       this.paciente = paciente;
    }
   
     @Id 

    
    @Column(name="login_user", nullable=false, length=30)
    public String getLoginUser() {
        return this.loginUser;
    }
    
    public void setLoginUser(String loginUser) {
        this.loginUser = loginUser;
    }

    
    @Column(name="login_password", nullable=false, length=50)
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="login")
    public Auxiliar getAuxiliar() {
        return this.auxiliar;
    }
    
    public void setAuxiliar(Auxiliar auxiliar) {
        this.auxiliar = auxiliar;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="login")
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }




}


