package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,schema="public"
)
public class Paciente  implements java.io.Serializable {


     private String pacId;
     private Login login;
     private String pacTipoId;
     private String pacApellido1;
     private String pacApellido2;
     private String pacNombres;
     private String pacEdad;
     private char pacSexo;
     private int pacUnidadEdad;
     private Date pacFechaNacimiento;
     private String pacOcupacion;
     private String pacCelular;
     private String pacTelefono;
     private String pacEmail;
     private String pacDireccion;
     private Date pacFechaRegistro;
     private boolean pacEstado;
     private Set<AntecedentesFamiliares> antecedentesFamiliareses = new HashSet<AntecedentesFamiliares>(0);
     private Set<AntecedentesPersonales> antecedentesPersonaleses = new HashSet<AntecedentesPersonales>(0);

    public Paciente() {
    }

	
    public Paciente(Login login, String pacTipoId, String pacApellido1, String pacApellido2, String pacNombres, String pacEdad, char pacSexo, int pacUnidadEdad, Date pacFechaNacimiento,String pacOcupacion, String pacCelular, String pacTelefono, String pacEmail, String pacDireccion, Date pacFechaRegistro, boolean pacEstado) {
        this.login = login;
        this.pacTipoId = pacTipoId;
        this.pacApellido1 = pacApellido1;
        this.pacApellido2 = pacApellido2;
        this.pacNombres = pacNombres;
        this.pacEdad = pacEdad;
        this.pacSexo = pacSexo;
        this.pacOcupacion = pacOcupacion;
        this.pacCelular = pacCelular;
        this.pacTelefono = pacTelefono;
        this.pacEmail = pacEmail;
        this.pacDireccion = pacDireccion;
        this.pacUnidadEdad = pacUnidadEdad;
        this.pacFechaNacimiento = pacFechaNacimiento;
        this.pacFechaRegistro = pacFechaRegistro;
        this.pacEstado = pacEstado;
    }
    public Paciente(Login login, String pacTipoId, String pacApellido1, String pacApellido2, String pacNombres, String pacEdad, char pacSexo, int pacUnidadEdad, Date pacFechaNacimiento, String pacOcupacion, String pacCelular, String pacTelefono, String pacEmail, String pacDireccion, Date pacFechaRegistro, boolean pacEstado, Set<AntecedentesFamiliares> antecedentesFamiliareses, Set<AntecedentesPersonales> antecedentesPersonaleses) {
       this.login = login;
       this.pacTipoId = pacTipoId;
       this.pacApellido1 = pacApellido1;
       this.pacApellido2 = pacApellido2;
       this.pacNombres = pacNombres;
       this.pacEdad = pacEdad;
       this.pacSexo = pacSexo;
       this.pacUnidadEdad = pacUnidadEdad;
       this.pacFechaNacimiento = pacFechaNacimiento;
       this.pacOcupacion = pacOcupacion;
       this.pacCelular = pacCelular;
       this.pacTelefono = pacTelefono;
       this.pacEmail = pacEmail;
       this.pacDireccion = pacDireccion;
       this.pacFechaRegistro = pacFechaRegistro;
       this.pacEstado = pacEstado;
       this.antecedentesFamiliareses = antecedentesFamiliareses;
       this.antecedentesPersonaleses = antecedentesPersonaleses;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="login"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="pac_id", nullable=false, length=30)
    public String getPacId() {
        return this.pacId;
    }
    
    public void setPacId(String pacId) {
        this.pacId = pacId;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    
    @Column(name="pac_tipo_id", nullable=false, length=10)
    public String getPacTipoId() {
        return this.pacTipoId;
    }
    
    public void setPacTipoId(String pacTipoId) {
        this.pacTipoId = pacTipoId;
    }

    
    @Column(name="pac_apellido1", nullable=false, length=50)
    public String getPacApellido1() {
        return this.pacApellido1;
    }
    
    public void setPacApellido1(String pacApellido1) {
        this.pacApellido1 = pacApellido1;
    }

    
    @Column(name="pac_apellido2", nullable=false, length=50)
    public String getPacApellido2() {
        return this.pacApellido2;
    }
    
    public void setPacApellido2(String pacApellido2) {
        this.pacApellido2 = pacApellido2;
    }

    
    @Column(name="pac_nombres", nullable=false, length=50)
    public String getPacNombres() {
        return this.pacNombres;
    }
    
    public void setPacNombres(String pacNombres) {
        this.pacNombres = pacNombres;
    }

    
    @Column(name="pac_edad", nullable=false, length=3)
    public String getPacEdad() {
        return this.pacEdad;
    }
    
    public void setPacEdad(String pacEdad) {
        this.pacEdad = pacEdad;
    }

    
    @Column(name="pac_sexo", nullable=false, length=1)
    public char getPacSexo() {
        return this.pacSexo;
    }
    
    public void setPacSexo(char pacSexo) {
        this.pacSexo = pacSexo;
    }

    
    @Column(name="pac_unidad_edad", nullable=false)
    public int getPacUnidadEdad() {
        return this.pacUnidadEdad;
    }
    
    public void setPacUnidadEdad(int pacUnidadEdad) {
        this.pacUnidadEdad = pacUnidadEdad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pac_fecha_nacimiento", nullable=false, length=13)
    public Date getPacFechaNacimiento() {
        return this.pacFechaNacimiento;
    }
    
    public void setPacFechaNacimiento(Date pacFechaNacimiento) {
        this.pacFechaNacimiento = pacFechaNacimiento;
    }

    
    @Column(name="pac_ocupacion", length=50)
    public String getPacOcupacion() {
        return this.pacOcupacion;
    }
    
    public void setPacOcupacion(String pacOcupacion) {
        this.pacOcupacion = pacOcupacion;
    }

    
    @Column(name="pac_celular", length=50)
    public String getPacCelular() {
        return this.pacCelular;
    }
    
    public void setPacCelular(String pacCelular) {
        this.pacCelular = pacCelular;
    }

    
    @Column(name="pac_telefono", length=50)
    public String getPacTelefono() {
        return this.pacTelefono;
    }
    
    public void setPacTelefono(String pacTelefono) {
        this.pacTelefono = pacTelefono;
    }

    
    @Column(name="pac_email", length=50)
    public String getPacEmail() {
        return this.pacEmail;
    }
    
    public void setPacEmail(String pacEmail) {
        this.pacEmail = pacEmail;
    }

    
    @Column(name="pac_direccion", length=50)
    public String getPacDireccion() {
        return this.pacDireccion;
    }
    
    public void setPacDireccion(String pacDireccion) {
        this.pacDireccion = pacDireccion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pac_fecha_registro", nullable=false, length=13)
    public Date getPacFechaRegistro() {
        return this.pacFechaRegistro;
    }
    
    public void setPacFechaRegistro(Date pacFechaRegistro) {
        this.pacFechaRegistro = pacFechaRegistro;
    }

    
    @Column(name="pac_estado", nullable=false)
    public boolean isPacEstado() {
        return this.pacEstado;
    }
    
    public void setPacEstado(boolean pacEstado) {
        this.pacEstado = pacEstado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<AntecedentesFamiliares> getAntecedentesFamiliareses() {
        return this.antecedentesFamiliareses;
    }
    
    public void setAntecedentesFamiliareses(Set<AntecedentesFamiliares> antecedentesFamiliareses) {
        this.antecedentesFamiliareses = antecedentesFamiliareses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set<AntecedentesPersonales> getAntecedentesPersonaleses() {
        return this.antecedentesPersonaleses;
    }
    
    public void setAntecedentesPersonaleses(Set<AntecedentesPersonales> antecedentesPersonaleses) {
        this.antecedentesPersonaleses = antecedentesPersonaleses;
    }




}


