package entity;
// Generated 15/06/2017 02:42:02 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * UnidadTiempo generated by hbm2java
 */
@Entity
@Table(name="unidad_tiempo"
    ,schema="public"
)
public class UnidadTiempo  implements java.io.Serializable {


     private int utId;
     private String utNombre;
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaCigarillo = new HashSet<AntecedentesPersonales>(0);
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaLicor = new HashSet<AntecedentesPersonales>(0);
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoLicor = new HashSet<AntecedentesPersonales>(0);
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias = new HashSet<AntecedentesPersonales>(0);
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias = new HashSet<AntecedentesPersonales>(0);
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica = new HashSet<AntecedentesPersonales>(0);
     private Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoCigarillo = new HashSet<AntecedentesPersonales>(0);

    public UnidadTiempo() {
    }

	
    public UnidadTiempo(String utNombre) {
        this.utNombre = utNombre;
    }
    public UnidadTiempo(String utNombre, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaCigarillo, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaLicor, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoLicor, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica, Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoCigarillo) {
       this.utNombre = utNombre;
       this.antecedentesPersonalesesForApUnidadFrecuenciaCigarillo = antecedentesPersonalesesForApUnidadFrecuenciaCigarillo;
       this.antecedentesPersonalesesForApUnidadFrecuenciaLicor = antecedentesPersonalesesForApUnidadFrecuenciaLicor;
       this.antecedentesPersonalesesForApUnidadHaceCuantoLicor = antecedentesPersonalesesForApUnidadHaceCuantoLicor;
       this.antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias = antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias;
       this.antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias = antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias;
       this.antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica = antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica;
       this.antecedentesPersonalesesForApUnidadHaceCuantoCigarillo = antecedentesPersonalesesForApUnidadHaceCuantoCigarillo;
    }
   
    @Id 
    @SequenceGenerator(name="pk_sequence",sequenceName="entity_id_seq", allocationSize=1)
    @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="pk_sequence")
    @Column(name="ut_id", nullable=false)
    public int getUtId() {
        return this.utId;
    }
    
    public void setUtId(int utId) {
        this.utId = utId;
    }

    
    @Column(name="ut_nombre", nullable=false, length=20)
    public String getUtNombre() {
        return this.utNombre;
    }
    
    public void setUtNombre(String utNombre) {
        this.utNombre = utNombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadFrecuenciaCigarillo")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadFrecuenciaCigarillo() {
        return this.antecedentesPersonalesesForApUnidadFrecuenciaCigarillo;
    }
    
    public void setAntecedentesPersonalesesForApUnidadFrecuenciaCigarillo(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaCigarillo) {
        this.antecedentesPersonalesesForApUnidadFrecuenciaCigarillo = antecedentesPersonalesesForApUnidadFrecuenciaCigarillo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadFrecuenciaLicor")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadFrecuenciaLicor() {
        return this.antecedentesPersonalesesForApUnidadFrecuenciaLicor;
    }
    
    public void setAntecedentesPersonalesesForApUnidadFrecuenciaLicor(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaLicor) {
        this.antecedentesPersonalesesForApUnidadFrecuenciaLicor = antecedentesPersonalesesForApUnidadFrecuenciaLicor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadHaceCuantoLicor")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadHaceCuantoLicor() {
        return this.antecedentesPersonalesesForApUnidadHaceCuantoLicor;
    }
    
    public void setAntecedentesPersonalesesForApUnidadHaceCuantoLicor(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoLicor) {
        this.antecedentesPersonalesesForApUnidadHaceCuantoLicor = antecedentesPersonalesesForApUnidadHaceCuantoLicor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadFrecuenciaOtrasSustancias")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias() {
        return this.antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias;
    }
    
    public void setAntecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias) {
        this.antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias = antecedentesPersonalesesForApUnidadFrecuenciaOtrasSustancias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadHaceCuantoOtrasSustancias")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias() {
        return this.antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias;
    }
    
    public void setAntecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias) {
        this.antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias = antecedentesPersonalesesForApUnidadHaceCuantoOtrasSustancias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadFrecuenciaActividadFisica")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadFrecuenciaActividadFisica() {
        return this.antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica;
    }
    
    public void setAntecedentesPersonalesesForApUnidadFrecuenciaActividadFisica(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica) {
        this.antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica = antecedentesPersonalesesForApUnidadFrecuenciaActividadFisica;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unidadTiempoByApUnidadHaceCuantoCigarillo")
    public Set<AntecedentesPersonales> getAntecedentesPersonalesesForApUnidadHaceCuantoCigarillo() {
        return this.antecedentesPersonalesesForApUnidadHaceCuantoCigarillo;
    }
    
    public void setAntecedentesPersonalesesForApUnidadHaceCuantoCigarillo(Set<AntecedentesPersonales> antecedentesPersonalesesForApUnidadHaceCuantoCigarillo) {
        this.antecedentesPersonalesesForApUnidadHaceCuantoCigarillo = antecedentesPersonalesesForApUnidadHaceCuantoCigarillo;
    }




}


